-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 05-Jul-2024 às 00:30
-- Versão do servidor: 10.4.32-MariaDB
-- versão do PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `life_health`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `signup`
--

CREATE TABLE `signup` (
  `Primeiro_Nome` varchar(30) NOT NULL,
  `Ultimo_Nome` varchar(30) NOT NULL,
  `NoCidadao` int(8) NOT NULL,
  `Password` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Extraindo dados da tabela `signup`
--

INSERT INTO `signup` (`Primeiro_Nome`, `Ultimo_Nome`, `NoCidadao`, `Password`) VALUES
('Rui', 'Inacio', 1234, '96f0f08c0188ba04898ce8cc465c19c4'),
('ISABEL', 'SALGUEIRO', 8554621, 'e22c17c60d56ae6c5afe04b4e26b563b'),
('Fernando', 'Salgueiro', 32137904, '25d55ad283aa400af464c76d713c07ad'),
('Jorge', 'Salgueiro', 456234987, 'b7a2c3b25c9441b0a38d0a874ace268b');

-- --------------------------------------------------------

--
-- Estrutura da tabela `sugestoes`
--

CREATE TABLE `sugestoes` (
  `Cod_sugestoes` int(11) NOT NULL,
  `coles_min` int(11) NOT NULL,
  `coles_max` int(11) NOT NULL,
  `genero` varchar(20) NOT NULL,
  `idade_min` int(11) NOT NULL,
  `idade_max` int(11) NOT NULL,
  `sugestao` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Extraindo dados da tabela `sugestoes`
--

INSERT INTO `sugestoes` (`Cod_sugestoes`, `coles_min`, `coles_max`, `genero`, `idade_min`, `idade_max`, `sugestao`) VALUES
(1, 0, 100, 'masculino', 0, 100, 'Aqui estão algumas sugestões para lidar com níveis baixos de colesterol:\r\n\r\nAlimentação\r\n Consuma gorduras saudáveis: Inclua gorduras \r\n saudáveis na sua dieta, como abacate, nozes, \r\n sementes, azeite de oliva e peixes gordurosos \r\n (salmão, sardinha).\r\nIncremente a ingestão de proteínas: \r\n Coma mais fontes de proteínas saudáveis como \r\n peixes, carnes magras, ovos e leguminosas.\r\nAumente a ingestão de frutas e vegetais: \r\n Esses alimentos são ricos em nutrientes e \r\n fibras, essenciais para a saúde geral.\r\nProdutos lácteos integrais: \r\n Considere incluir produtos lácteos integrais em \r\n vez de desnatados, pois contêm mais gordura e \r\n podem ajudar a aumentar o colesterol saudável.\r\nEstilo de Vida\r\n Exercício físico regular: Praticar atividades \r\n físicas regularmente pode ajudar a aumentar o \r\n colesterol HDL (colesterol \"bom\").\r\nEvite fumar: \r\n Se você fuma, parar pode melhorar os níveis de \r\n HDL.\r\nConsumo moderado de álcool: \r\n Beber álcool com moderação pode aumentar o \r\n colesterol HDL. Para adultos saudáveis, isso \r\n significa até uma bebida por dia para mulheres \r\n e até duas por dia para homens.\r\nSuplementos e Medicamentos\r\n Omega-3: Suplementos de óleo de peixe podem \r\n ajudar a aumentar os níveis de colesterol \r\n saudável.\r\nConsultar um médico: \r\n Se seus níveis de colesterol são extremamente \r\n baixos, é importante conversar com um \r\n profissional de saúde para descartar condições \r\n subjacentes e considerar tratamentos \r\n apropriados.\r\nMonitoramento\r\n Acompanhamento regular: Faça exames regulares \r\n para monitorar seus níveis de colesterol e \r\n garantir que estejam dentro de uma faixa \r\n saudável.\r\n Ajuste de dieta e estilo de vida: Baseado nos \r\n resultados dos exames, ajuste sua dieta e \r\n estilo de vida conforme necessário, sob \r\n orientação de um profissional de saúde.\r\nEssas sugestões são genéricas e podem não se aplicar a todos, especialmente se houver condições de saúde subjacentes. Sempre consulte um profissional de saúde antes de fazer mudanç'),
(2, 0, 100, 'feminino', 0, 100, 'Aqui estão algumas sugestões para lidar com níveis baixos de colesterol:\r\n\r\nAlimentação\r\n Consuma gorduras saudáveis: Inclua gorduras \r\n saudáveis na sua dieta, como abacate, nozes, \r\n sementes, azeite de oliva e peixes gordurosos \r\n (salmão, sardinha).\r\nIncremente a ingestão de proteínas: \r\n Coma mais fontes de proteínas saudáveis como \r\n peixes, carnes magras, ovos e leguminosas.\r\nAumente a ingestão de frutas e vegetais: \r\n Esses alimentos são ricos em nutrientes e \r\n fibras, essenciais para a saúde geral.\r\nProdutos lácteos integrais: \r\n Considere incluir produtos lácteos integrais em \r\n vez de desnatados, pois contêm mais gordura e \r\n podem ajudar a aumentar o colesterol saudável.\r\nEstilo de Vida\r\n Exercício físico regular: Praticar atividades \r\n físicas regularmente pode ajudar a aumentar o \r\n colesterol HDL (colesterol \"bom\").\r\nEvite fumar: \r\n Se você fuma, parar pode melhorar os níveis de \r\n HDL.\r\nConsumo moderado de álcool: \r\n Beber álcool com moderação pode aumentar o \r\n colesterol HDL. Para adultos saudáveis, isso \r\n significa até uma bebida por dia para mulheres \r\n e até duas por dia para homens.\r\nSuplementos e Medicamentos\r\n Omega-3: Suplementos de óleo de peixe podem \r\n ajudar a aumentar os níveis de colesterol \r\n saudável.\r\nConsultar um médico: \r\n Se seus níveis de colesterol são extremamente \r\n baixos, é importante conversar com um \r\n profissional de saúde para descartar condições \r\n subjacentes e considerar tratamentos \r\n apropriados.\r\nMonitoramento\r\n Acompanhamento regular: Faça exames regulares \r\n para monitorar seus níveis de colesterol e \r\n garantir que estejam dentro de uma faixa \r\n saudável.\r\n Ajuste de dieta e estilo de vida: Baseado nos \r\n resultados dos exames, ajuste sua dieta e \r\n estilo de vida conforme necessário, sob \r\n orientação de um profissional de saúde.\r\nEssas sugestões são genéricas e podem não se aplicar a todos, especialmente se houver condições de saúde subjacentes. Sempre consulte um profissional de saúde antes de fazer mudanç'),
(3, 101, 130, 'masculino', 0, 100, 'Manter uma dieta saudável e um estilo de vida ativo é crucial para sustentar esses níveis e promover a saúde cardiovascular em todas as idades. Aqui estão sugestões para manter e melhorar os níveis de colesterol:\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nInclua alimentos como aveia, feijão, lentilhas, maçãs, morangos e cítricos.\r\nEscolher gorduras saudáveis:\r\n\r\nPrefira gorduras insaturadas, como azeite de oliva, abacate, nozes e sementes.\r\nLimite gorduras saturadas e trans, que são encontradas em alimentos fritos, fast food e produtos industrializados.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nConsuma peixes gordurosos como salmão, cavala, sardinha e atum pelo menos duas vezes por semana.\r\nConsumir proteínas magras:\r\n\r\nOpte por carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, tempeh, feijões e lentilhas.\r\nLimitar alimentos ricos em colesterol:\r\n\r\nReduza o consumo de gemas de ovo e vísceras, como fígado.\r\nEscolha laticínios desnatados ou com baixo teor de gordura.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nPara crianças e adolescentes, pelo menos 60 minutos de atividade física moderada a vigorosa por dia.\r\nPara adultos, pelo menos 150 minutos de atividade física moderada ou 75 minutos de atividade vigorosa por semana.\r\nAtividades como caminhada, corrida, ciclismo, natação ou esportes são excelentes.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma combinação de alimentação saudável e exercício físico regular.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo é um fator de risco significativo para doenças cardiovasculares e pode afetar negativamente os níveis de colesterol.\r\nModeração no consumo de álcool:\r\n\r\nSe consumir álcool, faça-o com moderação. Para mulheres, até uma dose por dia; para homens, até duas doses por dia.\r\nControle do estresse:\r\n\r\nPratique técnicas de relaxamento como meditação, yoga, ou atividades que ajudem a reduzir o estresse.\r\nMonitoramento e Orie'),
(4, 101, 130, 'feminino', 0, 100, 'Manter uma dieta saudável e um estilo de vida ativo é crucial para sustentar esses níveis e promover a saúde cardiovascular em todas as idades. Aqui estão sugestões para manter e melhorar os níveis de colesterol:\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nInclua alimentos como aveia, feijão, lentilhas, maçãs, morangos e cítricos.\r\nEscolher gorduras saudáveis:\r\n\r\nPrefira gorduras insaturadas, como azeite de oliva, abacate, nozes e sementes.\r\nLimite gorduras saturadas e trans, que são encontradas em alimentos fritos, fast food e produtos industrializados.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nConsuma peixes gordurosos como salmão, cavala, sardinha e atum pelo menos duas vezes por semana.\r\nConsumir proteínas magras:\r\n\r\nOpte por carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, tempeh, feijões e lentilhas.\r\nLimitar alimentos ricos em colesterol:\r\n\r\nReduza o consumo de gemas de ovo e vísceras, como fígado.\r\nEscolha laticínios desnatados ou com baixo teor de gordura.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nPara crianças e adolescentes, pelo menos 60 minutos de atividade física moderada a vigorosa por dia.\r\nPara adultos, pelo menos 150 minutos de atividade física moderada ou 75 minutos de atividade vigorosa por semana.\r\nAtividades como caminhada, corrida, ciclismo, natação ou esportes são excelentes.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma combinação de alimentação saudável e exercício físico regular.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo é um fator de risco significativo para doenças cardiovasculares e pode afetar negativamente os níveis de colesterol.\r\nModeração no consumo de álcool:\r\n\r\nSe consumir álcool, faça-o com moderação. Para mulheres, até uma dose por dia; para homens, até duas doses por dia.\r\nControle do estresse:\r\n\r\nPratique técnicas de relaxamento como meditação, yoga, ou atividades que ajudem a reduzir o estresse.\r\nMonitoramento e Orie'),
(5, 131, 159, 'masculino', 20, 40, '1. Alimentação Saudável\n\nAumente o consumo de fibras: Inclua mais frutas, vegetais, legumes e grãos integrais na sua dieta. Alimentos ricos em fibras ajudam a reduzir os níveis de colesterol.\nEscolha gorduras saudáveis: Prefira gorduras insaturadas encontradas em azeite de oliva, abacate, nozes e peixes gordurosos como salmão e sardinha. Evite gorduras saturadas e trans encontradas em alimentos processados e fritos.\nConsuma proteínas magras: Opte por carnes magras, peixes, frango sem pele, ovos, e fontes vegetais de proteína como feijão e lentilhas.\nReduza o açúcar e carboidratos refinados: Evite bebidas açucaradas, doces, e pães feitos com farinha branca. Prefira carboidratos complexos como aveia, quinoa, e batata-doce.\n\n2. Exercício Regular\n\nAtividade aeróbica: Pratique pelo menos 150 minutos de exercícios aeróbicos de intensidade moderada por semana, como caminhar, correr, nadar ou andar de bicicleta.\n\nTreinamento de força: Inclua exercícios de musculação pelo menos duas vezes por semana para melhorar a massa muscular e o metabolismo.\n\n3. Manter o Peso Saudável\n\nControle de peso: Manter um peso saudável é crucial para o controle do colesterol.\nSe necessário, consulte um nutricionista para um plano de emagrecimento adequado.\n\n4. Evitar Fumo e Álcool em Excesso\nNão fume: \nO fumo pode aumentar os níveis de colesterol LDL (ruim) e diminuir os níveis de colesterol HDL (bom).\n\nLimite o consumo de álcool: Consuma álcool com moderação. Para homens, isso significa até duas bebidas por dia.\n\n5. Verificação Médica Regular\n\nExames regulares: Faça exames de sangue periódicos para monitorar os níveis de colesterol e outros indicadores de saúde cardiovascular.\n\nAcompanhamento médico: Consulte um médico regularmente para acompanhar sua saúde e receber orientações personalizadas.\n\n6. Gerenciamento de Estresse\n\nTécnicas de relaxamento: Pratique técnicas como meditação, ioga, ou respiração profunda para ajudar a reduzir o estresse, que pode afetar ne'),
(6, 0, 0, '0', 0, 0, 'Inicial'),
(7, 160, 189, 'feminino', 20, 40, 'Aqui estão algumas sugestões abrangentes para ajudar a gerenciar e reduzir os níveis de colesterol nesta faixa etária:\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nAlimentos como aveia, cevada, feijão, lentilhas, maçãs, peras e cítricos são ricos em fibras solúveis, que ajudam a reduzir o colesterol LDL (colesterol \"ruim\").\r\nEscolher gorduras saudáveis:\r\n\r\nUse azeite de oliva, abacate, nozes e sementes.\r\nEvite gorduras trans e limite as gorduras saturadas presentes em carnes vermelhas, manteiga e laticínios integrais.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nConsuma peixes gordurosos como salmão, cavala, sardinha e atum pelo menos duas vezes por semana.\r\nConsumir proteínas magras:\r\n\r\nPrefira carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, tempeh, feijões e lentilhas.\r\nLimitar alimentos ricos em colesterol:\r\n\r\nReduza o consumo de gemas de ovo e vísceras, como fígado.\r\nEscolha laticínios desnatados ou com baixo teor de gordura.\r\nAumentar o consumo de frutas e vegetais:\r\n\r\nFrutas e vegetais são ricos em nutrientes e fibras que ajudam a manter os níveis de colesterol sob controle.\r\nEvitar alimentos processados:\r\n\r\nReduza o consumo de alimentos processados e fast food, que são ricos em gorduras trans e saturadas.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nInclua pelo menos 150 minutos de atividade física moderada ou 75 minutos de atividade vigorosa por semana.\r\nAtividades como caminhada, corrida, ciclismo, natação ou esportes são excelentes.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma combinação de alimentação saudável e exercício físico regular.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo é um fator de risco significativo para doenças cardiovasculares e pode afetar negativamente os níveis de colesterol.\r\nModeração no consumo de álcool:\r\n\r\nSe consumir álcool, faça-o com moderação. Para mulheres, até uma dose por dia; para homens, até duas doses por dia.\r\nControle'),
(8, 131, 159, 'masculino', 0, 19, ' Aqui estão algumas sugestões para ajudar a gerenciar e melhorar os níveis de colesterol em jovens:\r\n\r\n Alimentação Saudável\r\nAumentar o consumo de fibras:\r\n\r\nInclua frutas, vegetais, grãos integrais e legumes na dieta.\r\nAlimentos ricos em fibras ajudam a reduzir o colesterol LDL (colesterol \"ruim\").\r\nEscolher gorduras saudáveis:\r\n\r\nPrefira gorduras insaturadas, como azeite de oliva, abacate, nozes e sementes.\r\nLimite o consumo de gorduras saturadas e trans, presentes em alimentos fritos, fast food, e produtos industrializados.\r\nConsumir proteínas magras:\r\n\r\nOpte por carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como feijão, lentilhas e tofu.\r\nEvitar alimentos ricos em colesterol:\r\n\r\nLimite a ingestão de alimentos ricos em colesterol, como fígado e outras vísceras, gemas de ovo e laticínios integrais.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nIncentive a prática de atividades físicas, como caminhada, corrida, ciclismo ou esportes.\r\nPelo menos 60 minutos de atividade física moderada a vigorosa por dia são recomendados para crianças e adolescentes.\r\nManter um peso saudável:\r\n\r\nAjude a manter um peso corporal adequado através de uma alimentação equilibrada e atividades físicas regulares.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo passivo também pode impactar negativamente os níveis de colesterol e a saúde cardiovascular.\r\nControle do estresse:\r\n\r\nIncentive técnicas de relaxamento, como yoga, meditação ou hobbies que reduzam o estresse.\r\nMonitoramento e Orientação Médica\r\nAcompanhamento regular com um profissional de saúde:\r\nRealize exames regulares para monitorar os níveis de colesterol.\r\nSiga as orien'),
(9, 131, 159, 'feminino', 0, 19, ' Aqui estão algumas sugestões para ajudar a gerenciar e melhorar os níveis de colesterol em jovens:\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras:\r\n\r\nInclua frutas, vegetais, grãos integrais e legumes na dieta.\r\nAlimentos ricos em fibras ajudam a reduzir o colesterol LDL (colesterol \"ruim\").\r\nEscolher gorduras saudáveis:\r\n\r\nPrefira gorduras insaturadas, como azeite de oliva, abacate, nozes e sementes.\r\nLimite o consumo de gorduras saturadas e trans, presentes em alimentos fritos, fast food, e produtos industrializados.\r\nConsumir proteínas magras:\r\n\r\nOpte por carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como feijão, lentilhas e tofu.\r\nEvitar alimentos ricos em colesterol:\r\n\r\nLimite a ingestão de alimentos ricos em colesterol, como fígado e outras vísceras, gemas de ovo e laticínios integrais.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nIncentive a prática de atividades físicas, como caminhada, corrida, ciclismo ou esportes.\r\nPelo menos 60 minutos de atividade física moderada a vigorosa por dia são recomendados para crianças e adolescentes.\r\nManter um peso saudável:\r\n\r\nAjude a manter um peso corporal adequado através de uma alimentação equilibrada e atividades físicas regulares.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo passivo também pode impactar negativamente os níveis de colesterol e a saúde cardiovascular.\r\nControle do estresse:\r\n\r\nIncentive técnicas de relaxamento, como yoga, meditação ou hobbies que reduzam o estresse.\r\nMonitoramento e Orientação Médica\r\nAcompanhamento regular com um profissional de saúde:\r\nRealize exames regulares para monitorar os níveis de colesterol.\r\nSiga as orien'),
(10, 131, 159, 'masculino', 41, 59, 'Alimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nAlimentos como aveia, feijão, lentilhas, maçãs, morangos e cítricos são ricos em fibras solúveis, que ajudam a reduzir o colesterol LDL.\r\nEscolher gorduras saudáveis:\r\n\r\nUse azeite de oliva, abacate, nozes e sementes.\r\nEvite gorduras trans e limite as gorduras saturadas presentes em carnes vermelhas, manteiga e laticínios integrais.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nConsuma peixes gordurosos como salmão, cavala, sardinha e atum pelo menos duas vezes por semana.\r\nConsumir proteínas magras:\r\n\r\nPrefira carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, tempeh, feijões e lentilhas.\r\nLimitar alimentos ricos em colesterol:\r\n\r\nReduza o consumo de gemas de ovo e vísceras, como fígado.\r\nEscolha laticínios desnatados ou com baixo teor de gordura.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nInclua pelo menos 150 minutos de atividade física moderada ou 75 minutos de atividade vigorosa por semana.\r\nAtividades como caminhada, corrida, ciclismo, natação ou esportes são excelentes.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma combinação de alimentação saudável e exercício físico regular.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo é um fator de risco significativo para doenças cardiovasculares e pode afetar negativamente os níveis de colesterol.\r\nModeração no consumo de álcool:\r\n\r\nSe consumir álcool, faça-o com moderação. Para mulheres, até uma dose por dia; para homens, até duas doses por dia.\r\nControle do estresse:\r\n\r\nPratique técnicas de relaxamento como meditação, yoga, ou atividades que ajudem a reduzir o estresse.\r\nMonitoramento e Orientação Médica\r\nAcompanhamento regular com um profissional de saúde:\r\n\r\nRealize exames de sangue regulares para monitorar os níveis de colesterol.\r\nSiga as orientações do médico ou nutricionista para ajustes na dieta e no estilo de vida.\r\nCheck-ups cardíacos:\r\n\r\nAvaliações regulares da saúde car'),
(11, 131, 159, 'feminino', 41, 59, 'Alimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nAlimentos como aveia, feijão, lentilhas, maçãs, morangos e cítricos são ricos em fibras solúveis, que ajudam a reduzir o colesterol LDL.\r\nEscolher gorduras saudáveis:\r\n\r\nUse azeite de oliva, abacate, nozes e sementes.\r\nEvite gorduras trans e limite as gorduras saturadas presentes em carnes vermelhas, manteiga e laticínios integrais.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nConsuma peixes gordurosos como salmão, cavala, sardinha e atum pelo menos duas vezes por semana.\r\nConsumir proteínas magras:\r\n\r\nPrefira carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, tempeh, feijões e lentilhas.\r\nLimitar alimentos ricos em colesterol:\r\n\r\nReduza o consumo de gemas de ovo e vísceras, como fígado.\r\nEscolha laticínios desnatados ou com baixo teor de gordura.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nInclua pelo menos 150 minutos de atividade física moderada ou 75 minutos de atividade vigorosa por semana.\r\nAtividades como caminhada, corrida, ciclismo, natação ou esportes são excelentes.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma combinação de alimentação saudável e exercício físico regular.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo é um fator de risco significativo para doenças cardiovasculares e pode afetar negativamente os níveis de colesterol.\r\nModeração no consumo de álcool:\r\n\r\nSe consumir álcool, faça-o com moderação. Para mulheres, até uma dose por dia; para homens, até duas doses por dia.\r\nControle do estresse:\r\n\r\nPratique técnicas de relaxamento como meditação, yoga, ou atividades que ajudem a reduzir o estresse.\r\nMonitoramento e Orientação Médica\r\nAcompanhamento regular com um profissional de saúde:\r\n\r\nRealize exames de sangue regulares para monitorar os níveis de colesterol.\r\nSiga as orientações do médico ou nutricionista para ajustes na dieta e no estilo de vida.\r\nCheck-ups cardíacos:\r\n\r\nAvaliações regulares da saúde car'),
(12, 131, 159, 'feminino', 60, 80, 'Para pessoas entre 60 e 80 anos com níveis de colesterol entre 131 e 159 mg/dL, é importante manter um estilo de vida saudável para prevenir problemas cardiovasculares e outras complicações de saúde.\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nAlimentos como aveia, cevada, feijões, lentilhas, maçãs, peras e cítricos são ricos em fibras solúveis, que ajudam a reduzir o colesterol LDL.\r\nEscolher gorduras saudáveis:\r\n\r\nPrefira gorduras insaturadas, como azeite de oliva, abacate, nozes e sementes.\r\nEvite gorduras trans e limite as gorduras saturadas encontradas em carnes vermelhas, manteiga e laticínios integrais.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nConsuma peixes gordurosos como salmão, cavala, sardinha e atum pelo menos duas vezes por semana.\r\nConsumir proteínas magras:\r\n\r\nOpte por carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, tempeh, feijões e lentilhas.\r\nLimitar alimentos ricos em colesterol:\r\n\r\nReduza o consumo de gemas de ovo e vísceras, como fígado.\r\nEscolha laticínios desnatados ou com baixo teor de gordura.\r\nIncluir alimentos funcionais:\r\n\r\nAlimentos como soja, nozes e sementes, além de produtos enriquecidos com esteróis e estanóis vegetais, podem ajudar a reduzir o colesterol.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nInclua pelo menos 150 minutos de atividade física moderada ou 75 minutos de atividade vigorosa por semana, conforme tolerado.\r\nAtividades de baixo impacto, como caminhadas, natação e yoga, são benéficas e apropriadas para essa faixa etária.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma combinação de alimentação saudável e exercício físico regular.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo é um fator de risco significativo para doenças cardiovasculares e pode afetar negativamente os níveis de colesterol.\r\nModeração no consumo de álcool:\r\n\r\nSe consumir álcool, faça-o com moderação. Para pessoas idosas, isso geralmente significa até'),
(13, 131, 159, 'feminino', 80, 100, 'manter a saúde cardiovascular continua sendo importante, mas as abordagens podem ser um pouco diferentes devido às necessidades específicas e a condições de saúde prevalentes nessa faixa etária. Aqui estão algumas sugestões para ajudar a gerenciar os níveis de colesterol e promover uma saúde geral:\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nFrutas, vegetais, grãos integrais e legumes ajudam a reduzir o colesterol LDL.\r\nInclua alimentos como aveia, cevada, maçãs, morangos e cítricos.\r\nEscolher gorduras saudáveis:\r\n\r\nPrefira gorduras insaturadas encontradas em azeite de oliva, abacate, nozes e sementes.\r\nLimite gorduras saturadas presentes em carnes vermelhas, manteiga e laticínios integrais. Evite gorduras trans.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nConsuma peixes como salmão, sardinha, cavala e atum pelo menos duas vezes por semana.\r\nAlternativas podem incluir suplementos de óleo de peixe, se apropriado.\r\nConsumir proteínas magras:\r\n\r\nOpte por carnes magras, frango sem pele e peixes.\r\nInclua fontes vegetais de proteína como feijão, lentilhas, tofu e tempeh.\r\nManter uma dieta balanceada:\r\n\r\nAssegure-se de que a dieta inclua uma variedade de nutrientes essenciais. Considerar suplementação de vitaminas e minerais se necessário, sob orientação médica.\r\nEstilo de Vida Ativo\r\nAtividade física regular:\r\n\r\nIncentive atividades físicas leves a moderadas, adaptadas à capacidade física da pessoa. Caminhadas, exercícios leves de alongamento, tai chi ou yoga são boas opções.\r\nConsulte um fisioterapeuta ou profissional de saúde para um plano de exercícios seguro e eficaz.\r\nManter um peso saudável:\r\n\r\nA combinação de uma dieta equilibrada e atividade física leve ajuda a manter um peso adequado.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nSe a pessoa fuma, é altamente recomendável parar, pois o tabagismo é um fator de risco significativo para doenças cardiovasculares.\r\nModeração no consumo de álcool:\r\n\r\nSe consumir álcool, faça-o com moderação. Para idosos, i'),
(14, 160, 189, 'masculino', 20, 40, 'Aqui estão algumas sugestões abrangentes para ajudar a gerenciar e reduzir os níveis de colesterol nesta faixa etária:\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nAlimentos como aveia, cevada, feijão, lentilhas, maçãs, peras e cítricos são ricos em fibras solúveis, que ajudam a reduzir o colesterol LDL (colesterol \"ruim\").\r\nEscolher gorduras saudáveis:\r\n\r\nUse azeite de oliva, abacate, nozes e sementes.\r\nEvite gorduras trans e limite as gorduras saturadas presentes em carnes vermelhas, manteiga e laticínios integrais.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nConsuma peixes gordurosos como salmão, cavala, sardinha e atum pelo menos duas vezes por semana.\r\nConsumir proteínas magras:\r\n\r\nPrefira carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, tempeh, feijões e lentilhas.\r\nLimitar alimentos ricos em colesterol:\r\n\r\nReduza o consumo de gemas de ovo e vísceras, como fígado.\r\nEscolha laticínios desnatados ou com baixo teor de gordura.\r\nAumentar o consumo de frutas e vegetais:\r\n\r\nFrutas e vegetais são ricos em nutrientes e fibras que ajudam a manter os níveis de colesterol sob controle.\r\nEvitar alimentos processados:\r\n\r\nReduza o consumo de alimentos processados e fast food, que são ricos em gorduras trans e saturadas.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nInclua pelo menos 150 minutos de atividade física moderada ou 75 minutos de atividade vigorosa por semana.\r\nAtividades como caminhada, corrida, ciclismo, natação ou esportes são excelentes.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma combinação de alimentação saudável e exercício físico regular.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo é um fator de risco significativo para doenças cardiovasculares e pode afetar negativamente os níveis de colesterol.\r\nModeração no consumo de álcool:\r\n\r\nSe consumir álcool, faça-o com moderação. Para mulheres, até uma dose por dia; para homens, até duas doses por dia.'),
(15, 160, 189, 'feminino', 0, 19, 'É importante tomar medidas para reduzir esses níveis de colesterol e promover hábitos saudáveis desde cedo. Aqui estão algumas sugestões específicas:\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nInclua alimentos como aveia, feijão, lentilhas, maçãs, morangos e cítricos, que são ricos em fibras solúveis e ajudam a reduzir o colesterol LDL (colesterol \"ruim\").\r\nEscolher gorduras saudáveis:\r\n\r\nUtilize gorduras insaturadas encontradas no azeite de oliva, abacate, nozes e sementes.\r\nEvite gorduras trans e limite o consumo de gorduras saturadas presentes em carnes vermelhas, manteiga e laticínios integrais.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nConsuma peixes gordurosos como salmão, cavala, sardinha e atum pelo menos duas vezes por semana.\r\nOptar por proteínas magras:\r\n\r\nPrefira carnes magras como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, tempeh, feijões e lentilhas.\r\nLimitar alimentos ricos em colesterol:\r\n\r\nReduza o consumo de gemas de ovo, vísceras (como fígado) e alimentos ricos em colesterol.\r\nEscolha laticínios desnatados ou com baixo teor de gordura.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nIncentive pelo menos 60 minutos de atividade física moderada a vigorosa todos os dias, como caminhar, correr, andar de bicicleta, nadar ou participar de esportes.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma combinação de alimentação saudável e exercício físico regular.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo, inclusive o fumo passivo, pode afetar negativamente os níveis de colesterol e a saúde cardiovascular.\r\nControle do estresse:\r\n\r\nIncentive técnicas de relaxamento como meditação, yoga, ou atividades que reduzam o estresse.\r\nMonitoramento e Orientação Médica\r\nAcompanhamento regular com um profissional de saúde:\r\n\r\nRealize exames regulares para monitorar os níveis de colesterol e outras métricas de saúde cardiovascular.\r\nSiga as orientações do médico ou nutricionista para a'),
(16, 160, 189, 'masculino', 0, 19, 'É importante tomar medidas para reduzir esses níveis de colesterol e promover hábitos saudáveis desde cedo. Aqui estão algumas sugestões específicas:\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nInclua alimentos como aveia, feijão, lentilhas, maçãs, morangos e cítricos, que são ricos em fibras solúveis e ajudam a reduzir o colesterol LDL (colesterol \"ruim\").\r\nEscolher gorduras saudáveis:\r\n\r\nUtilize gorduras insaturadas encontradas no azeite de oliva, abacate, nozes e sementes.\r\nEvite gorduras trans e limite o consumo de gorduras saturadas presentes em carnes vermelhas, manteiga e laticínios integrais.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nConsuma peixes gordurosos como salmão, cavala, sardinha e atum pelo menos duas vezes por semana.\r\nOptar por proteínas magras:\r\n\r\nPrefira carnes magras como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, tempeh, feijões e lentilhas.\r\nLimitar alimentos ricos em colesterol:\r\n\r\nReduza o consumo de gemas de ovo, vísceras (como fígado) e alimentos ricos em colesterol.\r\nEscolha laticínios desnatados ou com baixo teor de gordura.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nIncentive pelo menos 60 minutos de atividade física moderada a vigorosa todos os dias, como caminhar, correr, andar de bicicleta, nadar ou participar de esportes.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma combinação de alimentação saudável e exercício físico regular.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo, inclusive o fumo passivo, pode afetar negativamente os níveis de colesterol e a saúde cardiovascular.\r\nControle do estresse:\r\n\r\nIncentive técnicas de relaxamento como meditação, yoga, ou atividades que reduzam o estresse.\r\nMonitoramento e Orientação Médica\r\nAcompanhamento regular com um profissional de saúde:\r\n\r\nRealize exames regulares para monitorar os níveis de colesterol e outras métricas de saúde cardiovascular.\r\nSiga as orientações do médico ou nutricionista para a'),
(17, 160, 189, 'masculino', 41, 59, 'Manter e melhorar a saúde cardiovascular é crucial. Aqui estão sugestões para gerenciar esses níveis de colesterol:\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nFontes: Aveia, feijão, lentilhas, maçãs, frutas cítricas, brócolis, cenouras.\r\nBenefício: A fibra solúvel ajuda a reduzir o colesterol LDL (mau colesterol).\r\nEscolher gorduras saudáveis:\r\n\r\nFontes: Azeite de oliva, óleo de canola, abacate, nozes e sementes.\r\nBenefício: Substituir gorduras saturadas e trans por gorduras insaturadas pode melhorar o perfil lipídico.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nFontes: Salmão, cavala, sardinha, atum.\r\nBenefício: Ômega-3 ajuda a reduzir os níveis de triglicerídeos e pode aumentar o HDL (bom colesterol).\r\nConsumir proteínas magras:\r\n\r\nFontes: Peito de frango sem pele, peixe, cortes magros de carne vermelha, tofu, tempeh.\r\nBenefício: Proteínas magras contribuem para uma dieta balanceada sem aumentar significativamente os níveis de colesterol.\r\nReduzir alimentos ricos em colesterol:\r\n\r\nEvitar: Gemas de ovo (limite a 3-4 por semana), vísceras, frutos do mar ricos em colesterol como camarão e lagosta.\r\nSubstituir: Use claras de ovo, carnes magras e laticínios desnatados.\r\nAumentar o consumo de frutas e vegetais:\r\n\r\nBenefício: Fornecem fibras, vitaminas, minerais e antioxidantes que contribuem para a saúde cardiovascular.\r\nEstilo de Vida Ativo\r\nExercício físico regular:\r\n\r\nRecomendação: Pelo menos 150 minutos de atividade moderada ou 75 minutos de atividade vigorosa por semana.\r\nAtividades: Caminhada, corrida, ciclismo, natação, dança, esportes coletivos.\r\nManter um peso saudável:\r\n\r\nMétodo: Combine uma dieta equilibrada com atividade física regular.\r\nBenefício: Reduzir o peso corporal pode ajudar a diminuir os níveis de colesterol total e LDL.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nBenefício: Parar de fumar melhora os níveis de HDL e reduz o risco de doenças cardiovasculares.\r\nModeração no consumo de álcool:\r\n\r\nRecomendação: Até uma dose por dia para'),
(18, 160, 189, 'feminino', 41, 59, 'Manter e melhorar a saúde cardiovascular é crucial. Aqui estão sugestões para gerenciar esses níveis de colesterol:\r\n\r\nAlimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nFontes: Aveia, feijão, lentilhas, maçãs, frutas cítricas, brócolis, cenouras.\r\nBenefício: A fibra solúvel ajuda a reduzir o colesterol LDL (mau colesterol).\r\nEscolher gorduras saudáveis:\r\n\r\nFontes: Azeite de oliva, óleo de canola, abacate, nozes e sementes.\r\nBenefício: Substituir gorduras saturadas e trans por gorduras insaturadas pode melhorar o perfil lipídico.\r\nIncluir peixes ricos em ômega-3:\r\n\r\nFontes: Salmão, cavala, sardinha, atum.\r\nBenefício: Ômega-3 ajuda a reduzir os níveis de triglicerídeos e pode aumentar o HDL (bom colesterol).\r\nConsumir proteínas magras:\r\n\r\nFontes: Peito de frango sem pele, peixe, cortes magros de carne vermelha, tofu, tempeh.\r\nBenefício: Proteínas magras contribuem para uma dieta balanceada sem aumentar significativamente os níveis de colesterol.\r\nReduzir alimentos ricos em colesterol:\r\n\r\nEvitar: Gemas de ovo (limite a 3-4 por semana), vísceras, frutos do mar ricos em colesterol como camarão e lagosta.\r\nSubstituir: Use claras de ovo, carnes magras e laticínios desnatados.\r\nAumentar o consumo de frutas e vegetais:\r\n\r\nBenefício: Fornecem fibras, vitaminas, minerais e antioxidantes que contribuem para a saúde cardiovascular.\r\nEstilo de Vida Ativo\r\nExercício físico regular:\r\n\r\nRecomendação: Pelo menos 150 minutos de atividade moderada ou 75 minutos de atividade vigorosa por semana.\r\nAtividades: Caminhada, corrida, ciclismo, natação, dança, esportes coletivos.\r\nManter um peso saudável:\r\n\r\nMétodo: Combine uma dieta equilibrada com atividade física regular.\r\nBenefício: Reduzir o peso corporal pode ajudar a diminuir os níveis de colesterol total e LDL.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nBenefício: Parar de fumar melhora os níveis de HDL e reduz o risco de doenças cardiovasculares.\r\nModeração no consumo de álcool:\r\n\r\nRecomendação: Até uma dose por dia para'),
(19, 190, 1000, 'feminino', 0, 100, 'Alimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nAlimentos ricos em fibras solúveis, como aveia, cevada, feijão, lentilhas, maçãs, peras e frutas cítricas, podem ajudar a reduzir o colesterol LDL.\r\nEscolher gorduras saudáveis:\r\n\r\nUse azeite de oliva, abacate, nozes e sementes em vez de gorduras saturadas e trans.\r\nEvite alimentos processados e frituras, que são ricos em gorduras trans.\r\nConsumir peixes ricos em ômega-3:\r\n\r\nInclua peixes como salmão, sardinha, atum e cavala na dieta pelo menos duas vezes por semana.\r\nEscolher proteínas magras:\r\n\r\nPrefira carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, feijão, lentilhas e nozes.\r\nReduzir o consumo de colesterol dietético:\r\n\r\nLimite a ingestão de alimentos ricos em colesterol, como gemas de ovo, fígado e outros órgãos.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nPelo menos 150 minutos de atividade física moderada ou 75 minutos de atividade vigorosa por semana para adultos.\r\nCrianças e adolescentes devem ter pelo menos 60 minutos de atividade física moderada a vigorosa diariamente.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma alimentação equilibrada e exercícios físicos regulares.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo é um fator de risco significativo para doenças cardiovasculares e pode aumentar os níveis de colesterol LDL.\r\nModeração no consumo de álcool:\r\n\r\nSe consumir álcool, faça-o com moderação. Para mulheres, até uma dose por dia; para homens, até duas doses por dia.\r\nControle do estresse:\r\n\r\nPratique técnicas de relaxamento como meditação, yoga, ou atividades que ajudam a reduzir o estresse.\r\nMonitoramento e Orientação Médica\r\nAcompanhamento regular com um profissional de saúde:\r\n\r\nRealize exames de sangue regulares para monitorar os níveis de colesterol.\r\nSiga as orientações do médico ou nutricionista para ajustes na dieta e no estilo de vida.\r\nCheck-ups cardíacos:\r\n\r\nAvaliações regulares da saúde card'),
(20, 190, 1000, 'masculino', 0, 100, 'Alimentação Saudável\r\nAumentar o consumo de fibras solúveis:\r\n\r\nAlimentos ricos em fibras solúveis, como aveia, cevada, feijão, lentilhas, maçãs, peras e frutas cítricas, podem ajudar a reduzir o colesterol LDL.\r\nEscolher gorduras saudáveis:\r\n\r\nUse azeite de oliva, abacate, nozes e sementes em vez de gorduras saturadas e trans.\r\nEvite alimentos processados e frituras, que são ricos em gorduras trans.\r\nConsumir peixes ricos em ômega-3:\r\n\r\nInclua peixes como salmão, sardinha, atum e cavala na dieta pelo menos duas vezes por semana.\r\nEscolher proteínas magras:\r\n\r\nPrefira carnes magras, como frango sem pele e peixe.\r\nInclua fontes vegetais de proteína, como tofu, feijão, lentilhas e nozes.\r\nReduzir o consumo de colesterol dietético:\r\n\r\nLimite a ingestão de alimentos ricos em colesterol, como gemas de ovo, fígado e outros órgãos.\r\nEstilo de Vida Ativo\r\nPraticar atividades físicas regularmente:\r\n\r\nPelo menos 150 minutos de atividade física moderada ou 75 minutos de atividade vigorosa por semana para adultos.\r\nCrianças e adolescentes devem ter pelo menos 60 minutos de atividade física moderada a vigorosa diariamente.\r\nManter um peso saudável:\r\n\r\nControle o peso através de uma alimentação equilibrada e exercícios físicos regulares.\r\nHábitos Saudáveis\r\nEvitar o tabagismo:\r\n\r\nO fumo é um fator de risco significativo para doenças cardiovasculares e pode aumentar os níveis de colesterol LDL.\r\nModeração no consumo de álcool:\r\n\r\nSe consumir álcool, faça-o com moderação. Para mulheres, até uma dose por dia; para homens, até duas doses por dia.\r\nControle do estresse:\r\n\r\nPratique técnicas de relaxamento como meditação, yoga, ou atividades que ajudam a reduzir o estresse.\r\nMonitoramento e Orientação Médica\r\nAcompanhamento regular com um profissional de saúde:\r\n\r\nRealize exames de sangue regulares para monitorar os níveis de colesterol.\r\nSiga as orientações do médico ou nutricionista para ajustes na dieta e no estilo de vida.\r\nCheck-ups cardíacos:\r\n\r\nAvaliações regulares da saúde card');

-- --------------------------------------------------------

--
-- Estrutura da tabela `utentes`
--

CREATE TABLE `utentes` (
  `Nome` varchar(150) NOT NULL,
  `Idade` int(3) NOT NULL,
  `NoCidadao` int(20) NOT NULL,
  `Número` int(13) NOT NULL,
  `Morada` varchar(100) NOT NULL,
  `Genero` varchar(20) NOT NULL,
  `Diabetes` int(5) NOT NULL,
  `Colesterol` int(5) NOT NULL,
  `Cod_sugestoes` int(11) DEFAULT 6
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Extraindo dados da tabela `utentes`
--

INSERT INTO `utentes` (`Nome`, `Idade`, `NoCidadao`, `Número`, `Morada`, `Genero`, `Diabetes`, `Colesterol`, `Cod_sugestoes`) VALUES
('ISABEL MARIA BERNARDO SALGUEIRO FERREIRA', 38, 8554621, 963622198, 'RUA SILVINO ANDRADE DA SILVA, 2', 'masculino', 120, 136, 5),
('Fernando Rodrigo Salgueiro Ferreira', 17, 32137904, 961357538, 'rua alves redol', 'masculino', 120, 102, 3),
('Jorge salgueiro', 40, 456234987, 987678098, 'avenida Brasil', 'masculino', 200, 40, 1);

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `signup`
--
ALTER TABLE `signup`
  ADD PRIMARY KEY (`NoCidadao`);

--
-- Índices para tabela `sugestoes`
--
ALTER TABLE `sugestoes`
  ADD PRIMARY KEY (`Cod_sugestoes`);

--
-- Índices para tabela `utentes`
--
ALTER TABLE `utentes`
  ADD PRIMARY KEY (`NoCidadao`),
  ADD KEY `Cod_sugestoes` (`Cod_sugestoes`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `sugestoes`
--
ALTER TABLE `sugestoes`
  MODIFY `Cod_sugestoes` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

--
-- Restrições para despejos de tabelas
--

--
-- Limitadores para a tabela `utentes`
--
ALTER TABLE `utentes`
  ADD CONSTRAINT `utentes_ibfk_1` FOREIGN KEY (`NoCidadao`) REFERENCES `signup` (`NoCidadao`),
  ADD CONSTRAINT `utentes_ibfk_2` FOREIGN KEY (`Cod_sugestoes`) REFERENCES `sugestoes` (`Cod_sugestoes`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
